---
title: "biography"
---

I previously studied German & Linguistics at the University of Edinburgh, where I developed an interest in British Sign Language (BSL) and sign language linguistics, taking my first BSL course at [Deaf Action](http://www.deafaction.org.uk/). 

In my second year I helped run SignSoc, the student BSL society at Edinburgh. Later that year I undertook a research internship at the [Deafness Cognition and Language Research Centre](http://www.ucl.ac.uk/dcal) at UCL with Dr Robin Thompson.

While on my exchange year I worked as a language assistant and took my first module in psycholinguistics at Eberhard-Karls-Universit&auml;t T&uuml;bingen. I also took courses in German Sign Language (DGS) in Hamburg & T&uuml;bingen. 

On my return to Scotland I wrote my MA dissertation on auditory attention and visuospatial cognition in bimodal bilinguals, supervised by [Prof Antonella Sorace](https://www.ed.ac.uk/profile/antonella-sorace) and [Dr Thomas Bak](https://www.ed.ac.uk/profile/thomas-bak), while working on my BSL Level 3 at Deaf Action.

After graduating I returned to Germany, where I continued to learn DGS while working as a German translator and English tutor, before receiving ESRC studentship funding for a MSc and PhD with Dr Robin Thompson, now at the University of Birmingham.

My master's dissertation was on phonological processing of speech and sign input in hearing bimodal bilinguals (who know both English and BSL).

Since 2015 I have been working on my PhD part-time. Find out more [here](https://freyawatkins.github.io/phd.html) 