---
title: "other work"
---

* I am currently the primary research assistant for the [Online Reading Research Project](http://www.ssc.education.ed.ac.uk/research/onlinereading/) about web-based reading strategies in deaf and hearing teenagers. I have collected and coded eyetracking, 'think aloud' and language assessment data for the project in a number of locations including Edinburgh, London, Brighton and Birmingham. The project is a collaboration between the University of Edinburgh, University of Roehampton & University of Birmingham and is funded by the British Academy, ESRC and Leverhulme Trust. 

* Since spring 2017 I have been a research assistant in Dr Robin Thompson's M2L2 lab. This has mainly involved data collection and coding for a variety of sign language processing and production studies, including behavioural, eyetracking and electromyography methodologies.

* Within the School of Psychology I have taught the course 'Introduction to E-Prime' and I am the Teaching Assistant for the postgraduate module 'Transferable Skills'. I also invigilate exams for the Undergraduate Office.

* Since 2013 I have worked as a self-employed German-English translator and proofreader. I have experience translating a range of texts, varying from academic studies to technical datasheets to children's fiction. I proofread academic essays written in English, particularly those written by German native speakers.

* I also have 10 years' experience working as an audio transcriber. I have worked for [Take Note Typing](https://www.takenotetyping.com/), [Amara (Universal Subtitles)](https://amara.org/en/) and a range of individual clients including academics and businesses.

* If you need any transcription, translation or proofreading work done, feel free to contact me! 