---
title: "on-stage presentations"
---

* O’Neill, R., Thompson, R. L., **Watkins, F.**, Mann. W., (2021). Strategies used by deaf and hearing children during online reading: insights from an eye-tracking study. 23rd International Congress on the Education of the Deaf, Brisbane, Australia, 5th July 2021.

* **Watkins, F.**, & Thompson, R. L. (2019). Comprehension in hearing non-signers from angle-diverse learning input. Theoretical Issues in Sign Language Research 13, Universit&auml;t Hamburg, Germany, 26th September 2019.

* **Watkins, F.**, & Thompson, R. L. (2019). Comprehension of angle-diverse British Sign Language input in novice L2 learners. EuroSLA 29, Lunds universitet, Sweden, 31st August 2019.

* **Watkins, F.** (2019). Angle diverse input and sign vocabulary learning in novice L2 British Sign Language Learners. School of Psychology Research Conference, University of Birmingham, UK, 30th April 2019.

* **Watkins, F.**, Abdlkarim, D., & Thompson, R. L. (2018). The nature of L1 & L2 phonological representations in a signed language: 3D or orientation-specific? International Society for Gesture Studies 8, Cape Town, South Africa, 5th July 2018.

* **Watkins, F.**, Abdlkarim, D., & Thompson, R. L. (2018). L1 and L2 sign recognition: the role of visual angle. 3rd Intnl. Conference on Sign Language Acquisition, Ko&ccedil; &Uuml;niversitesi, Istanbul, Turkey, 28th June 2018.

* Thompson, R.L & **Watkins, F.** (2018). The Role of Visual Angle on L2 Learning in British Sign Language. Leverhulme Network on Sign Language as Second Languages Project, 4th meeting, Humboldt Universit&auml;t zu Berlin, Germany, 19th March 2018.

* Thompson, R.L & **Watkins, F.** (2016). The relationship between sign production and sign comprehension: what the hands reveal. International Society for Gesture Studies Conference 7, Paris, France, 19th July 2016.

* **Watkins, F.**, & Thompson, R. L. (2015). Phonological Processing of Dual Language Input: The relationship between phonological systems for speech-sign bilinguals. 58. Studentische Tagung Sprachwissenschaft, Goethe-Universit&auml;t Frankfurt, Germany, 19th November 2015.

* **Watkins, F.** (2015). Die Britische Geb&auml;rdensprache (BSL) und die Deutsche Geb&auml;rdensprache (DGS) im Vergleich. Workshop at the 58. Studentische Tagung Sprachwissenschaft, Goethe-Universit&auml;t Frankfurt, Germany, 18th November 2015.

* **Watkins, F.** (2013). Bi-bi, bilingual advantage? Attention and visuospatial cognition in late bimodal bilinguals. 54. Studentische Tagung Sprachwissenschaft (StuTS), Heinrich-Heine-Universit&auml;t D&uuml;sseldorf, Germany, 15th November 2013.

* Thompson, R. L., **Watkins, F.** & Vigliocco, G. (2013). The relationship between sign production and sign comprehension: what the hands reveal. Theoretical Issues in Sign Language Research 11, University College London, UK, 11th July 2013.

* **Watkins, F.** (2013). Bi-bi, bilingual advantage? Attention and visuospatial cognition in late bimodal bilinguals. 3rd Undergraduate Linguistics Association of Great Britain Conference, University of York, UK, 27th April 2013.

* **Watkins, F.** (2013). Ibid. Linguistics and English Language Dissertation Conference, University of Edinburgh, UK, 25th April 2013.

* **Watkins, F.** & Thompson, R. L. (2012). Investigating Handedness Effects on Perception in British Sign Language. 51. Studentische Tagung Sprachwissenschaft (StuTS), Universit&auml;t Stuttgart, Germany, 17th May 2012.  
  
<br/>

# poster presentations  

  
* Thompson, R. L., **Watkins, F.**, Mann. W., & O’Neill, R. (2018). Strategies used by deaf and hearing children during online reading. Workshop on Reading, Language & Deafness, Basque Center on Cognition, Brain and Language, San Sebastian, Spain, 18th October 2018.

* **Watkins, F.**, Abdlkarim, D. & Thompson, R. L. (2017). Viewpoint specificity in L1 and L2 British Sign Language comprehension. Architectures and Mechanisms of Language Processing 2017, University of Lancaster, UK, 9th September 2017.

* **Watkins, F.**, Abdlkarim, D. & Thompson, R. L. (2017). Ibid. Postgraduate Research Event, School of Psychology, University of Birmingham, UK, 24th April 2017.

* **Watkins, F.**, & Thompson, R. L. (2016). Phonological Processing of Dual Language Input: The relationship between phonological systems for speech-sign bilinguals. Theoretical Issues in Sign Language Research 12, Melbourne, Australia, 6th January 2016.

* **Watkins, F.**, Sorace, A. & Bak, T. (2015) Bi-bi, bilingual advantage? Auditory attention and visuospatial cognition in late L2 bimodal bilinguals. 2nd International Conference on Sign Language Acquisition, Universiteit van Amsterdam, The Netherlands, 1st July 2015.

* **Watkins, F.**, Scholes, L., Sandher, A. & Wheeldon, L. (2015). Semantically-related naming in two picture-picture interference tasks. Psychology Postgraduate Poster Conference, University of Birmingham, UK, 13th April 2015.